/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readreview;

/**
 *
 * @author ACER
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

public class WaterActivityReview extends javax.swing.JFrame {

    /**
     * Creates new form WaterActivityReview
     */
    public WaterActivityReview() {
        initComponents();
        messageLow.setWrapStyleWord(true);
        messageLow.setLineWrap(true);
        messageHigh.setWrapStyleWord(true);
        messageHigh.setLineWrap(true);
        setLocationRelativeTo(null); // Frame appear on Center of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        nameHigh = new javax.swing.JLabel();
        nameLow = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        scoreHigh = new javax.swing.JLabel();
        scoreLow = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageLow = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageHigh = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Water Activity Review", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36))); // NOI18N

        nameHigh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameHigh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameHigh.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        nameLow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLow.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        scoreHigh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scoreHigh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreHigh.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        scoreLow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scoreLow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLow.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        messageLow.setColumns(20);
        messageLow.setRows(5);
        jScrollPane1.setViewportView(messageLow);

        messageHigh.setColumns(20);
        messageHigh.setRows(5);
        jScrollPane2.setViewportView(messageHigh);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameLow, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scoreLow, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scoreHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2)
                    .addComponent(nameHigh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreHigh, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreLow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        ReadReviewUI rev1 = new ReadReviewUI();
        rev1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //testFile2 obj = new testFile2();
        
        String Path = "C:\\Users\\Adib Zaini\\Desktop\\CS230 PART 3\\CSC483\\Project\\New Folder\\project\\src\\main\\java\\database\\water_review.txt";
        
        //List<Trend> trends = obj.readFile(Paths.get("C:/Users/ACER/Desktop/sem 3/CSC435/project/test.txt"), ";;;");
        //trends.forEach(System.out::println);
        int size = 0;
        try 
        {
            Scanner readFile = new Scanner(new File(Path));
            
            while (readFile.hasNextLine())  
            {
                //String[] line = readFile.nextLine().split(";;;");
                size++;
                readFile.nextLine();
            }
        } catch (IOException ex) {
            Logger.getLogger(WaterActivityReview.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String []name = new String[size];
        String []rating = new String[size];
        String []comment = new String[size];
        int i = 0;
        
        //List<Trend> result = new ArrayList<>();
        try 
        {
            Scanner readFile = new Scanner(new File(Path));
            
            while (readFile.hasNextLine()) 
            {
                    
                    name[i] = "";
                    rating[i] = "";
                    comment[i] = "";
                    String[] line = readFile.nextLine().split(";;;");
                    
                    name[i] = line[0];
                    rating[i] = line[1];
                    comment[i] = line[2];
                    //result.add(new Trend(name, rating, comment));
                    i++;
            }
        } catch (IOException ex) {
            Logger.getLogger(WaterActivityReview.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.print(name[0]);
        int bb[] = new int[size];
        for (int a=0; a<size; a++)
        {
            bb[a] = Integer.parseInt(rating[a]);
        }
        
        int high = bb[0], low = bb[0], indexHigh = 0, indexLow = 0;
        for (int j=0; j<size; j++)
        {
            if (bb[j] > high)
            {
                high = bb[j];
                indexHigh = j;
            }
            else if (bb[j] < low)
            {
                low = bb[j];
                indexLow = j;
            }
        }
        nameHigh.setText(name[indexHigh]);
        scoreHigh.setText(rating[indexHigh]);
        messageHigh.setText(comment[indexHigh]);
        nameLow.setText(name[indexLow]);
        scoreLow.setText(rating[indexLow]);
        messageLow.setText(comment[indexLow]);
        
        //return result;
        
        //private String name;
        //private Double rating;
        //private String comment;
        
        /*public Trend(String name, Double rating, String comment)
        {
            this.name = name;
            this.rating = rating;
            this.comment = comment;
        }*/
        
        //@Override
        /*public String toString()
        {
            return "Name: " + name + ", rating: " + rating + ", comment: " + comment;
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaterActivityReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaterActivityReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaterActivityReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaterActivityReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaterActivityReview().setVisible(true);
            }
        });
        WaterActivityReview obj = new WaterActivityReview();
        List<Trend> trends = obj.readFile(Paths.get("C:/Users/ACER/Desktop/sem 3/CSC435/project/test.txt"), ";;;");
    }
    
    public List<Trend> readFile(Path path, String delimiter) throws IOException
    {
        List<Trend> result = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(path.toString())))
        {
            String line;
            while ((line = br.readLine()) != null) 
            {
                StringTokenizer st = new StringTokenizer(line, delimiter);
                while (st.hasMoreTokens())
                {
                    String name = st.nextToken().trim();
                    Double rating = Double.parseDouble(st.nextToken().trim());
                    String comment = st.nextToken().trim();
                    result.add(new Trend(name,rating, comment));
                }
            }
        }
        return result;
    }
    
    class Trend
    {
        private String name;
        private Double rating;
        private String comment;
        
        public Trend(String name, Double rating, String comment)
        {
            this.name = name;
            this.rating = rating;
            this.comment = comment;
        }
        
        /*@Override
        public String toString()
        {
            return "Name: " + name + ", rating: " + rating + ", comment: " + comment;
        }*/
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messageHigh;
    private javax.swing.JTextArea messageLow;
    private javax.swing.JLabel nameHigh;
    private javax.swing.JLabel nameLow;
    private javax.swing.JLabel scoreHigh;
    private javax.swing.JLabel scoreLow;
    // End of variables declaration//GEN-END:variables
}
